# Generated by Django 3.2.4 on 2021-06-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='periodicity',
            field=models.CharField(choices=[('yearly', 'yearly'), ('monthly', 'monthly'), ('weekly', 'weekly'), ('daily', 'daily'), ('one-off', 'one-off')], default='one-off', max_length=10),
        ),
    ]
