# Generated by Django 3.2.4 on 2021-06-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.event'),
        ),
    ]
