# Generated by Django 3.2.4 on 2021-06-08 04:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_alter_transaction_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Payment',
        ),
    ]
