# Generated by Django 3.2.4 on 2021-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_ticketsleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticketsleft',
            name='date',
            field=models.DateField(),
        ),
    ]
